export enum DragonAura {
    "Breath of Milk" = 1,
    "Dragon Cursor" = 2,
    "Elder Battalion" = 3,
    "Reaper of Fields" = 4,
    "Earth Shatterer" = 5,
    "Master of the Armory" = 6,
    "Fierce Hoarder" = 7,
    "Dragon God" = 8,
    "Arcane Aura" = 9,
    "Dragonflight" = 10,
    "Ancestral Metamorphosis" = 11,
    "Unholy Dominion" = 12,
    "Epoch Manipulator" = 13,
    "Mind Over Matter" = 14,
    "Radiant Appetite" = 15,
    "Dragon's Fortune" = 16,
    "Dragon's Curve" = 17,
    "Reality Bending" = 18,
    "Dragon Orbs" = 19,
    "Supreme Intellect" = 20,
    "Dragon Guts" = 21,
}

export const DragonAuraRequiredLevel: Record<DragonAura, number> = {
    [DragonAura["Breath of Milk"]]: 5,
    [DragonAura["Dragon Cursor"]]: 6,
    [DragonAura["Elder Battalion"]]: 7,
    [DragonAura["Reaper of Fields"]]: 8,
    [DragonAura["Earth Shatterer"]]: 9,
    [DragonAura["Master of the Armory"]]: 10,
    [DragonAura["Fierce Hoarder"]]: 11,
    [DragonAura["Dragon God"]]: 12,
    [DragonAura["Arcane Aura"]]: 13,
    [DragonAura.Dragonflight]: 14,
    [DragonAura["Ancestral Metamorphosis"]]: 15,
    [DragonAura["Unholy Dominion"]]: 16,
    [DragonAura["Epoch Manipulator"]]: 17,
    [DragonAura["Mind Over Matter"]]: 18,
    [DragonAura["Radiant Appetite"]]: 19,
    [DragonAura["Dragon's Fortune"]]: 20,
    [DragonAura["Dragon's Curve"]]: 21,
    [DragonAura["Reality Bending"]]: 22,
    [DragonAura["Dragon Orbs"]]: 23,
    [DragonAura["Supreme Intellect"]]: 24,
    [DragonAura["Dragon Guts"]]: 25,
};