import { Buff } from "./Buff";
import { Fortune } from "./Fortune";
import { MinigameType } from "./MinigameType";
import { Shimmer } from "./Shimmer";
import { Ticker } from "./Ticker";
import { Upgrade } from "./Upgrade";
import { Wrinkler } from "./Wrinkler";

export interface Game {
    baseSeason: string;
    prestige: number;
    lumps: number;
    BuildingsOwned: number;
    UpgradesOwned: number;
    lumpRipeAge: number;
    lumpT: number;
    dragonAura2: number;
    dragonAura: number;
    santaLevels: string[];
    season: string;
    seasonUses: number;
    specialTab: string;
    ready: boolean;
    cookies: number;
    cookiesPs: number;
    globalCpsMult: number;
    shimmers: Shimmer[];
    Objects: Record<string, any>;
    UpgradesInStore: Upgrade[];
    magic: number;
    buffs: Record<string, Buff>;
    TickerEffect: 0 | Fortune;
    tickerL: Ticker;
    dragonLevel: number;
    Achievements: Record<string, { won: boolean }>;
    dragonLevels: any[];
    Upgrades: any;
    UpgradesById: any;
    santaLevel: number;
    wrinklers: Wrinkler[];
    isMinigameReady(minigame: MinigameType): boolean;
    getWrinklersMax(): number;
    canLumps(): boolean;
    clickLump(): void;
    UpgradeSanta(): void;
    crateTooltip(u: Upgrade, location: string): string;
    ClickCookie(): void;
    hasBuff(name: string): boolean;
    ToggleSpecialMenu(arg0: number): void;
    ClickSpecialPic(): void;
    HasUnlocked(drop: string): boolean;
    Has(drop: string): 0 | 1;
    SetDragonAura(arg0: number, arg1: number): void;
    ConfirmPrompt(): void;
    UpgradeDragon(): void;
    CollectWrinklers(): void;
}